from __future__ import annotations

from ._version import PHASE, __version__

PACKAGE_VERSION = __version__
PACKAGE_PHASE = PHASE
CANONICAL_RUNTIME_AGENT_ID = "super-advisor"
RUNTIME_AGENT_IDS = (
    "super-advisor",
    "xau-strategy-auditor",
    "system-coder-auditor",
    "telegram-publisher",
)
AGENT_SKILL_NAMES = {
    "super-advisor": (
        "advisor-safety-contract",
        "environment-health",
        "evidence-audit",
        "agent-orchestration-contract",
        "super-potential-review",
        "incident-reporting",
        "publication-policy",
    ),
    "xau-strategy-auditor": (
        "xauusd-market-analysis",
        "multi-timeframe-structure-review",
        "price-action-order-block",
        "chart-pattern-filter-review",
        "candlestick-microstructure",
        "strategy-logic-audit",
        "realtime-evidence-review",
        "super-potential-audit",
        "alert-quality-improvement",
    ),
    "system-coder-auditor": (
        "python-pipeline-micro-audit",
        "code-architecture-review",
        "logic-conflict-detection",
        "dead-code-and-duplicate-review",
        "test-and-regression-design",
        "blueprint-compliance-audit",
        "safe-patch-workflow",
        "release-and-rollback",
        "skill-improvement-proposal",
    ),
    "telegram-publisher": (
        "thai-telegram-publisher",
        "telegram-message-contract",
        "telegram-delivery-safety",
        "telegram-deduplication-throttle",
        "telegram-retry-and-dead-letter",
        "telegram-security-redaction",
    ),
}
SKILL_NAMES = tuple(
    skill for agent_id in RUNTIME_AGENT_IDS for skill in AGENT_SKILL_NAMES[agent_id]
)
SKILL_OWNERS = {
    skill: agent_id for agent_id, skills in AGENT_SKILL_NAMES.items() for skill in skills
}
AGENT_ALLOWED_TOOLS = {
    "super-advisor": ("read", "session_status"),
    "xau-strategy-auditor": ("read", "session_status"),
    "system-coder-auditor": ("read", "session_status"),
    "telegram-publisher": ("read", "session_status"),
}
AGENT_DENIED_TOOLS = {
    "super-advisor": (
        "group:runtime",
        "group:web",
        "group:ui",
        "group:automation",
        "group:messaging",
        "group:plugins",
        "group:memory",
        "group:sessions",
        "write",
        "edit",
        "apply_patch",
        "exec",
        "process",
        "code_execution",
        "browser",
        "canvas",
        "gateway",
        "message",
        "subagents",
        "memory_search",
        "memory_get",
        "sessions_list",
        "sessions_history",
        "sessions_send",
        "sessions_spawn",
        "sessions_yield",
    ),
    "xau-strategy-auditor": (
        "group:runtime",
        "group:web",
        "group:ui",
        "group:automation",
        "group:messaging",
        "group:plugins",
        "group:memory",
        "group:sessions",
        "write",
        "edit",
        "apply_patch",
        "exec",
        "process",
        "code_execution",
        "browser",
        "canvas",
        "gateway",
        "message",
        "subagents",
        "memory_search",
        "memory_get",
        "sessions_list",
        "sessions_history",
        "sessions_send",
        "sessions_spawn",
        "sessions_yield",
    ),
    "system-coder-auditor": (
        "group:runtime",
        "group:web",
        "group:ui",
        "group:automation",
        "group:messaging",
        "group:plugins",
        "group:memory",
        "group:sessions",
        "write",
        "edit",
        "apply_patch",
        "exec",
        "process",
        "code_execution",
        "browser",
        "canvas",
        "gateway",
        "message",
        "subagents",
        "memory_search",
        "memory_get",
        "sessions_list",
        "sessions_history",
        "sessions_send",
        "sessions_spawn",
        "sessions_yield",
    ),
    "telegram-publisher": (
        "group:runtime",
        "group:web",
        "group:ui",
        "group:automation",
        "group:messaging",
        "group:plugins",
        "group:memory",
        "group:sessions",
        "write",
        "edit",
        "apply_patch",
        "exec",
        "process",
        "code_execution",
        "browser",
        "canvas",
        "gateway",
        "message",
        "subagents",
        "memory_search",
        "memory_get",
        "sessions_list",
        "sessions_history",
        "sessions_send",
        "sessions_spawn",
        "sessions_yield",
    ),
}
FORBIDDEN_SYMBOLS = (
    "order_send",
    "order_check",
    "TRADE_ACTION",
    "ExecutionKernel",
    "execution_kernel",
    "execution_dispatch_bridge",
    "position_close",
    "close_position",
    "modify_order",
    "cancel_order",
    "execute_order",
    "auto_trade",
)
FORBIDDEN_TRACKED_PATHS = (
    r"state\.env",
    r"state\openclaw.json",
    r"state\credentials",
    r"state\sessions",
    r"state\logs",
    r"\.venv",
    r"logs",
    r"data\runtime",
    r"archive",
)
ENV_STATUSES = ("PRESENT", "MISSING", "BLANK", "INVALID_FORMAT")
